[package]
name = "js-components"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
wasmparser = "0.84.0"
serde_json = "1.0.80"
serde = { version = "1.0.137", features = ["derive"] }
