[package]
name = "js-components"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.57"
serde_json = "1.0.80"
serde = { version = "1.0.137", features = ["derive"] }
wasm-bindgen = "0.2"
wasmparser = "0.84.0"

