version = 0.1
default-task = 'build'

[[task]]
name = 'build'
deps = [':build:wasm']

[[task]]
name = 'build:wasm'
serial = true
deps = ['wasm/pkg/js_components_wasm.js', 'wasm/pkg/component-compiler-wasm.js', 'wasm/pkg/package.json']

[[task]]
target = 'wasm/pkg/js_components_wasm.js'
deps = ['crates/js-components/src/*.rs', 'wasm/src/*.rs', 'Cargo.toml']
run = 'wasm-pack build --target web wasm'

[[task]]
target = 'wasm/pkg/component-compiler-wasm.js'
dep = 'wasm/component-compiler-wasm.js'
run = 'cp $DEP $TARGET'

[[task]]
invalidation = 'always'
target = 'wasm/pkg/package.json'
dep = 'wasm/package.json'
run = 'cp $DEP $TARGET'
